{% set version = "1.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rmariadb
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RMariaDB_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RMariaDB/RMariaDB_{{ version }}.tar.gz
  sha256: c97c61ace584f9ad9929d3e3f366556e0eecad12bc98ea2979563a01475f468e

build:
  number: 4
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-dbi                        # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-bit64                      # [build_platform != target_platform]
    - r-blob                       # [build_platform != target_platform]
    - r-hms                        # [build_platform != target_platform]
    - r-lubridate                  # [build_platform != target_platform]
    - r-plogr                      # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dbi >=1.1.0
    - r-rcpp >=0.12.4
    - r-bit64
    - r-blob
    - r-hms >=0.5.0
    - r-lubridate
    - r-plogr
    - r-rlang
    - mysql-connector-c
  run:
    - r-base
    - r-dbi >=1.1.0
    - r-rcpp >=0.12.4
    - r-bit64
    - r-blob
    - r-hms >=0.5.0
    - r-lubridate
    - r-plogr
    - r-rlang
    - mysql-connector-c

test:
  requires:
    - r-testthat
    - r-dbitest >=1.7.0
    - r-readr
    - r-withr
  source_files:
    - tests/
  commands:
    - $R -e "library('RMariaDB')"                                                     # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('RMariaDB')\""                                            # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://downloads.mariadb.org/connector-c/
  dev_url: https://github.com/r-dbi/RMariaDB
  license: MIT
  summary: Implements a 'DBI'-compliant interface to 'MariaDB' (<https://mariadb.org/>) and 'MySQL' (<https://www.mysql.com/>) databases.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc
