appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: PSYzTKHIQLSIMV1f/LGCK4p4KOG+6/EkZMZnsjQ74nUn31FJgq3wG39Dp70iBAuqhY9Xb0DGkXiROpih3zoBuwm1qguYZn1cJggEfxsO81zNqZZm4K/WhdKRxefDbNV4zqhX64ShWDQYZMT2ggegB5ikkId6AwJUu17jGS2kZ5/k2cejAnxRTq3kfcfsZdIhEk1n+Gzq8sNVWbYAUlPn1mjOKSberHz/I3ruz0TBWj/gw0ECVitmMh6tYOPAbDlEWa6k7fcLUkrlL/PAnvsjpbUFAnlCI97LmWRdykHD13P2b7z80SPvs4drASSf4sXNAx2PGuxXWlsO47KTFhSJiYAzDYA2f5u/SWULpO89jUyPVaBRH5L6Q+7WOzeUGt6s7oxWq5dO3f1EoMiwR+ERCY+E/b4aZUPfWAotfSdicG4Iih5xXVWJXqPKsK2Jzvmeod7+amSAsVAcr6KXWLbX6ZLGTWAKQbDIooKnhraXg/G5q/S1+G0An0mA98CI0UQ80dYn19sFNtBDOW9QG+qzs2Cg45L4gugoixXA19zrila6FWYo3+9tUix7qTQKEoTh1C0UV+5IYo3AIb/WnlzyT35rbd5E6cKof/qo9FIyZtJ2Kx1hp66vU0dUa2U6zuiAX+PwXfLD4+F5OYafLehnFfzeLRJf9TdNzCNlmUwDLrE=}
bot:
  automerge: true
